package com.vmatrix.constant;

public enum Command
{
	INITIALIZATION, LOGIN, SHOW_CONTENT, SWITCH_TO_SETTINGS_ACTIVITY, LOGOUT, DESTORY, BACK, RESTART, PAUSE, STOP, RESUME, LAYOUT_PORTRAIT, LAYOUT_LANDSCAPE, OPEN_NETWORK_CONFIG_DIALOG, CONFIG_NETWORK,CHARTS
}
