package com.vmatrix.constant;

public enum LoginError
{
	PASSWORD_ERROR, RET_MSG_ERROR, USERNAME_ERROR, ACCOUNT_OVERDUE_ERROR, ONLINE_MAX_ERROR, OEM_OVERDUE_ERROR, SERVER_ERROR, CONNECTION_TIMEOUT_ERROR, VIDEOLIST_TIMEOUT_ERROR, QKT_CONNECTION_FAILURE, QKT_ERROR

}
